export const REQUEST_CONVERSATIONS = 'REQUEST_CONVERSATIONS';
export const REQUEST_CONVERSATIONS_SUCCESS = 'REQUEST_CONVERSATIONS_SUCCESS';
export const REQUEST_CONVERSATIONS_ERROR = 'REQUEST_CONVERSATIONS_ERROR';

export const REQUEST_SINGLE_CONVERSATION = 'REQUEST_CONVERSATION';
export const REQUEST_SINGLE_CONVERSATION_SUCCESS = 'REQUEST_CONVERSATION_SUCCESS';
export const REQUEST_SINGLE_CONVERSATION_ERROR = 'REQUEST_CONVERSATION_ERROR';